// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8hNwLR3Q1hnSBO_hdJWymGQMJ-3PJXY',
    appId: '1:14126510268:web:5e3c9aa87609edc2e4e0b9',
    messagingSenderId: '14126510268',
    projectId: 'quotealine-67587',
    authDomain: 'quotealine-67587.firebaseapp.com',
    storageBucket: 'quotealine-67587.appspot.com',
    measurementId: 'G-CF9C9R0RXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgPTPpicQvZw_T3QhseOhxlee4wvojlY0',
    appId: '1:14126510268:android:d29864b701b55139e4e0b9',
    messagingSenderId: '14126510268',
    projectId: 'quotealine-67587',
    storageBucket: 'quotealine-67587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0C-GJlDd8iNrJr7IYUQIE57bYRDEYyg0',
    appId: '1:14126510268:ios:e2467517d3bf9515e4e0b9',
    messagingSenderId: '14126510268',
    projectId: 'quotealine-67587',
    storageBucket: 'quotealine-67587.appspot.com',
    iosBundleId: 'com.example.quotealineHoly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0C-GJlDd8iNrJr7IYUQIE57bYRDEYyg0',
    appId: '1:14126510268:ios:0f32cb3c25c0ae7ee4e0b9',
    messagingSenderId: '14126510268',
    projectId: 'quotealine-67587',
    storageBucket: 'quotealine-67587.appspot.com',
    iosBundleId: 'com.example.quotealineHoly.RunnerTests',
  );
}
